struct CONFIG
{
    int SERIAL_BOUD_RATE = 115200, GPS_SERIAL_BOUD_RATE = 9600, PROTOCOL_STRING_LENGTH = 16, PROTOCOL_DATA_START_INDEX = 3, PROTOCOL_DATA_END_INDEX = 13, PROTOCOL_IDENTIFIER_START_INDEX = 0, PROTOCOL_IDENTIFIER_END_INDEX = 3, PROTOCOL_CR = 13, PROTOCOL_LF = 10;
    String PROTOCOL_IDENTIFIER = "INF", PROTOCOL_ANY_VALUE_VALID = "ANY_VALUE";
    String PROTOCOL_ALLOWED_ELEMENTS_VALUES[14] = {"I", "N", "F", "01", "N1234567890", "CN", "x", "x", "x", "x", "x", "x", "x", PROTOCOL_ANY_VALUE_VALID};
    byte GPS_RX = 16, GPS_TX = 17;
    char PROTOCOL_DO_NOT_DOSE = 'N', PROTOCOL_DO_NOT_CLEAR_WHELL_BOLT_COUNTS = 'N', ALARM_SIREN_OFF = '0';
};
