#include "exceptions/error-type.h"

ERROR_TYPES::ERROR_TYPES()
{
    VALIDATION_ERROR = new ERROR_TYPE("ERR REQ INVALIDO", "001");
    DOSE_PROCESS_TIME_OUT = new ERROR_TYPE("ERR DOSE TIMEOUT", "002");
    GPS_TIME_OUT = new ERROR_TYPE("ERR GPS TIMEOUT", "003");
    PARSE_ERROR = new ERROR_TYPE("ERR PARSE", "004");
    NO_APPLICATORS_FOUND_ERROR = new ERROR_TYPE("ERR CON. DOSADOR", "005");
    this->ERROR_TYPES_ARRAY[0] = *VALIDATION_ERROR;
    this->ERROR_TYPES_ARRAY[1] = *DOSE_PROCESS_TIME_OUT;
    this->ERROR_TYPES_ARRAY[2] = *GPS_TIME_OUT;
    this->ERROR_TYPES_ARRAY[3] = *PARSE_ERROR;
    this->ERROR_TYPES_ARRAY[4] = *NO_APPLICATORS_FOUND_ERROR;
};
