#ifndef EXCEPTIONS_H
#define EXCEPTIONS_H
#include "error-type.h"
struct EXCEPTIONS
{
    ERROR_TYPE VALIDATION_ERROR = ERROR_TYPE("PROTOCOLO INVALI.", ERROR_CODE().VALIDATION_ERROR);
    ERROR_TYPE DOSE_PROCESS_TIME_OUT = ERROR_TYPE("DOSE LENTA", ERROR_CODE().DOSE_PROCESS_TIME_OUT);
    ERROR_TYPE GPS_TIME_OUT = ERROR_TYPE("GPS SEM RESPOSTA", ERROR_CODE().GPS_TIME_OUT);
    ERROR_TYPE PARSE_ERROR = ERROR_TYPE("ERRO PARSE", ERROR_CODE().PARSE_ERROR);
    ERROR_TYPE NO_APPLICATORS_FOUND_ERROR = ERROR_TYPE("CONEXAO DOSADOR", ERROR_CODE().NO_APPLICATORS_FOUND_ERROR);
    ERROR_TYPE RENAME_ERROR = ERROR_TYPE("ERRO AO RENOMEAR", ERROR_CODE().NO_APPLICATORS_FOUND_ERROR);
};

#endif