#ifndef EXCEPTIONS_H
#define EXCEPTIONS_H
#include "error-type.h"
struct EXCEPTIONS
{
    ERROR_TYPE VALIDATION_ERROR = ERROR_TYPE("ERR REQ INVALIDO", ERROR_CODE().VALIDATION_ERROR);
    ERROR_TYPE DOSE_PROCESS_TIME_OUT = ERROR_TYPE("ERR DOSE TIMEOUT", ERROR_CODE().DOSE_PROCESS_TIME_OUT);
    ERROR_TYPE GPS_TIME_OUT = ERROR_TYPE("ERR GPS TIMEOUT", ERROR_CODE().GPS_TIME_OUT);
    ERROR_TYPE PARSE_ERROR = ERROR_TYPE("ERR PARSE", ERROR_CODE().PARSE_ERROR);
    ERROR_TYPE NO_APPLICATORS_FOUND_ERROR = ERROR_TYPE("ERR CON. DOSADOR", ERROR_CODE().NO_APPLICATORS_FOUND_ERROR);
};

#endif